### PR TITLE
Fix for #504

### LINKED ISSUE #504: Inconsistent Problems Arise When Installing New Version of Tethys

### PR DESCRIPTION
**Pull request by sdc50**
workaround fix for the intermittent Django startup errors. Fixes #504

### CODE REVIEW

File: scripts/install_tethys.sh [hunk 1]
```diff
@@ -530,9 +522,9 @@ then
 
     echo "export NGINX_USER='${NGINX_USER}'" >> "${ACTIVATE_SCRIPT}"
     echo "export NGINX_HOME='${NGINX_HOME}'" >> "${ACTIVATE_SCRIPT}"
-    echo "alias tethys_user_own='sudo chown -R \${USER} \"\${TETHYS_SRC}\" \"\${TETHYS_HOME}/static\" \"\${TETHYS_HOME}/workspaces\" \"\${TETHYS_HOME}/apps\"'" >> "${ACTIVATE_SCRIPT}"
+    echo "alias tethys_user_own='sudo chown -R \${USER} \"${TETHYS_SRC}\" \"${TETHYS_HOME}/static\" \"${TETHYS_HOME}/workspaces\" \"${TETHYS_HOME}/apps\"'" >> "${ACTIVATE_SCRIPT}"
```
Comment (swainn) [inline scripts/install_tethys.sh]: Are ``TETHYS_SRC`` and ``TETHYS_HOME`` defined in this script still?

Comment (swainn) [reply scripts/install_tethys.sh]: The SERVIR folks rely pretty heavily on these aliases for managing their manual deploys.

Comment (sdc50) [reply scripts/install_tethys.sh]: Yes, both `TETHYS_SRC` and `TETHYS_HOME` are defined in the install script, but I have removed them from the activate script. The changes here have the effect of substituting the values for those variables when the activate scripts are written, rather than writing the variable names in the script so they are substituted at runtime.

**Comment by sdc50** [comment]
> The ALLOWED_HOSTS section of the portal_config.yml isn't formatted correctly when installing from the script.

It looks like the script was not passing in the `ALLOWED_HOSTS` argument as a list. This should be fixed now.
